name: Test form
description: Made this to test something
body:
  - type: markdown
    attributes:
      value: |
        Found a mistake? Where is it?

  - type: textarea
    id: one
    attributes:
      label: A form
      description: The form description
      
  - type: textarea
    id: two
    attributes:
      label: Another form
      description: Second description
      placeholder: More text
