name: Test form
description: Made this to test something
body:
  - type: markdown
    attributes:
      value: Found a mistake? Where is it?

  - type: input
    id: one
    attributes:
      label: A form
      description: The form's description
      placeholder: "I hope the "quotation marks" don't do anything bad"
    validations:
      
    - type: input
    id: two
    attributes:
      label: Another form
      description: "Second description"
      placeholder: |
        More text with "quotation marks"
    validations:
